baseurl = "/"
languageCode = "en-us"
theme = "terminal"

# Hugo 0.128+ requires pagination section
[pagination]
  pagerSize = 5

# Allow raw HTML in markdown (for embeds like Gists, iframes)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Hugo 0.120+ requires services configuration
[services]
  [services.googleAnalytics]
    id = "UA-44665454-3"
  # [services.disqus]
  #   shortname = "biancarosablog"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en]
    languageName = "english"
    title = "biancarosa.com.br"
    subtitle = "staff platform engineer"
    keywords = "senior,developer,engineer,backend,infrastructure,infra,devops,staff,open source,startup"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "biancarosa.com.br"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "_self"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "blog-en"
        name = "blog"
        url = "/"

      [[languages.en.menu.main]]
        identifier = "talks"
        name = "talks"
        url = "/talks"

      [[languages.en.menu.main]]
        identifier = "recommendations"
        name = "tech content recommendations"
        url = "/recommendations"

      [[languages.en.menu.main]]
        identifier = "bluesky"
        name = "bluesky"
        url = "https://bsky.app/profile/bianca-rosa.bsky.social"

      [[languages.en.menu.main]]
        identifier = "fediverse"
        name = "fediverse"
        url = "https://hachyderm.io/@bia"

      [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/biancarosa"

      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/biarm"

      [[languages.en.menu.main]]
        identifier = "substack"
        name = "substack"
        url = "https://backendengineeringadventures.substack.com"

      [[languages.en.menu.main]]
        identifier = "x"
        name = "x"
        url = "https://twitter.com/__biancarosa"

  [languages.pt]
    languageName = "português [brasil]"
    title = "biancarosa.com.br"
    subtitle = "staff platform engineer"
    keywords = "senior,developer,engineer,backend,infrastructure,infra,platform,devops,staff,open source,startup"
    copyright = ""
    menuMore = "ver mais"
    readMore = "ler mais"
    readOtherPosts = "ler outros posts"

    [languages.pt.params.logo]
      logoText = "biancarosa.com.br"
      logoHomeLink = "/pt"

    [languages.pt.menu]
      [[languages.pt.menu.main]]
        identifier = "blog-pt"
        name = "blog"
        url = "/pt"

      [[languages.pt.menu.main]]
        identifier = "talks"
        name = "palestras & apresentações"
        url = "/talks"

      [[languages.pt.menu.main]]
        identifier = "aprenda-go"
        name = "aprendago.com.br"
        url = "https://aprendago.com.br"

      [[languages.pt.menu.main]]
        identifier = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/biarm"

      [[languages.pt.menu.main]]
        identifier = "x"
        name = "x"
        url = "https://twitter.com/__biancarosa"

      [[languages.pt.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/biancarosa"

      [[languages.pt.menu.main]]
        identifier = "bluesky"
        name = "bluesky"
        url = "https://bsky.app/profile/bianca-rosa.bsky.social"

      [[languages.pt.menu.main]]
        identifier = "substack"
        name = "substack"
        url = "https://backendengineeringadventures.substack.com"

      [[languages.pt.menu.main]]
        identifier = "fediverse"
        name = "fediverse"
        url = "https://hachyderm.io/@bia"